version: "3.9"
services:
  wifi-sentinel-linux:
    build: .
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./frontend:/app/frontend
      - ./backend/plugins:/app/backend/plugins
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - linux

  wifi-sentinel-mac:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./frontend:/app/frontend
      - ./backend/plugins:/app/backend/plugins
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - mac

  wifi-sentinel-demo:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./frontend:/app/frontend
      - ./backend/plugins:/app/backend/plugins
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - DEMO=1
    profiles:
      - demo
